spring.application.name=proyectofinal

# Port del servidor
server.port=8090

# URL de conexión (el puerto por defecto es 5432)
spring.datasource.url=jdbc:postgresql://ep-dawn-flower-b4uloyhw-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZsKzeOrkJm59
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto para PostgreSQL (recomendado para asegurar compatibilidad de tipos de datos)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Crea o actualiza tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update